first Version of Predict Training

diff --git a/PredictKMTraining b/PredictKMTraining
--- a/PredictKMTraining
+++ b/PredictKMTraining
@@ -2,20 +2,20 @@
 predictDir=../predictkm
 tmpdir=`mktemp -d -t predict-XXXXXXXX`
 input=$1
+model=$2
 validation=$predictDir/NpData/Visbo/ValidationData.json
 output=$tmpdir/predictTrainingOutput.json
 error=$tmpdir/predictTrainingError
 
-echo python3 $predictDir/NpDeploy/NpIncrementModels.py -i $input -p $predictDir -v $validation -m RandomForestRegressor -q NpQFinalCost1 -c Visbo
-python3 $predictDir/NpDeploy/NpIncrementModels.py -i $input -p $predictDir -v $validation -m RandomForestRegressor -q NpQFinalCost1 -c Visbo
-# > $output 2> $error
+# echo python3 $predictDir/NpDeploy/NpIncrementModels.py -i $input -p $predictDir -v $validation -d $model -q NpQFinalCost1 -c Visbo
+python3 $predictDir/NpDeploy/NpIncrementModels.py -i $input -p $predictDir -v $validation -d $model -q NpQFinalCost1 -c Visbo > $output 2> $error
 
-#if [ $? -ne 0 ]
-#then
-#  echo "FATAL: PredictBACTraining failed" 1>&2
-#  cat $error 1>&2
-#  exit 1
-#fi
-#echo "" >>$output
-#cat <$output
-# rm -rf $tmpdir
+if [ $? -ne 0 ]
+then
+  echo "FATAL: PredictBACTraining failed" 1>&2
+  cat $error 1>&2
+  exit 1
+fi
+# echo "" >>$output
+cat <$output
+rm -rf $tmpdir
